### PR TITLE
Add missing appveyor MinGW configurations

### PR DESCRIPTION
**Pull request by ericLemanissier**
enable x86 and add gcc8

### CODE REVIEW

**Comment by theirix** [comment]
Looks good, thanks. I remember some problems with some mingw builds but this build works fine on Appveyor. Waiting for finished builds…

**Comment by ericLemanissier** [comment]
The problems you had were probably fixed by conan-community/conan-mingw-installer#21

**Review by SSE4 — APPROVED** [review]
LGTM

**Comment by theirix** [comment]
@ericLemanissier very possible, thanks

**Pull request merged**
