### PR TITLE
Fixed cross compiling with mingw on non-windows host.

### PR DESCRIPTION
**Pull request by MB3hel**
The conanfile sets the host and built triplets when using mingw (now only with a windows host). This allows cross building from linux (as the host setting based on the conan profile is preserved).

It would be good to merge this into the stable branch too.

### CODE REVIEW

**Comment by theirix** [comment]
Good idea. So `settings.os` is a target OS (like `--host` in autotools) and `platform.system()` is a build OS (like `--build` in autotools).
@SSE4 @solvingj how do you think, should we port this to other recipes as well?

**Comment by SSE4** [comment]
I believe **AutoToolsBuildEnvionment** helper should set correct triplet itself by default (it was already  added few months ago) and code in recipe setting **x86_64-w64-mingw32** should be already unnecessary. I believe we could try to remove it, if it will not work, then fix conan's function (**tools.get_gnu_triplet**)

**Comment by theirix** [comment]
Yes, forgot about it. I'll try to do it in this recipe.

**Comment by theirix** [comment]
@MB3hel could you please test the `testing/9c` branch? Proposed change should fix your problem.

**Comment by MB3hel** [comment]
@theirix This will work if line 49 uses `platform.system()` to check if win_bash should be used. As it is now cross compilation will fail with the following output becuase win_bash is only valid when building on windows (I fixed this in my fork as well, but I forgot to mention it here. Sorry about that.)

```
ERROR: libjpeg/9c@bincrafters/testing: Error in build() method, line 69
        self.build_configure()
while calling 'build_configure', line 61
        env_build.configure(configure_dir=self.source_subfolder, args=config_args)
        ConanException: Command only for Windows operating system
```

**Comment by theirix** [comment]
@MB3hel fair enough, added the condition. Please check it.

**Comment by MB3hel** [comment]
That fixes the issue thanks.

**Comment by theirix** [comment]
Added the same workaround for some other mingw-enabled recipes (libjpeg-turbo, giflib).

**Pull request closed without merging**
